sudo: required
language: java
language: kotlin
jdk:
- oraclejdk8

script:
- "./gradlew build"

before_install:
- chmod a+x gradlew

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  apt: true
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
